# Generated by Django 4.1.3 on 2022-11-06 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='articles',
            new_name='Article',
        ),
    ]
