# Generated by Django 4.1.3 on 2022-11-06 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_article_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='email',
        ),
    ]
